### ISSUE TITLE
Device selection while running Sapienz

### ISSUE THREAD

**Issue by giograno** [lucaspelloni2/BA_PROJ#15]
I'd propose to change the mechanism for switching between Emulator and Device on Sapienz.

I'd call the Python Sapienz part with a second argument like the following (in `main.py` file):

```
if __name__ == "__main__":
    app_dir = sys.argv[1]
    is_emulator = sys.argv[2]
    main(app_dir, is_emulator)
```

And then I'd handle the choice in `main.py` from LOC 277 to 302.

**Comment by lucaspelloni2** [comment]
This issue has been extended to the whole project. 
The main arguments passed to the command line differentiate with which tool the experiment is going to be executed (monkey/sapienz), which is the testing mode (emulator / device) and if there is a timer set for the whole experiment.

**Comment by lucaspelloni2** [comment]
**Command Line Example:**
java -jar /Users/LuckyP/Desktop/UZH/BA/BA_PROJ/out/artifacts/BA_PROJECT_jar/BA_PROJECT.jar -device -monkey -timer
